#ifndef CAR_LOOP_H
#define CAR_LOOP_H

#include "zf_common_headfile.h"

/* 遥控轴已标准化到[-1000, 1000]，使用径向迟滞死区抑制中心方向跳变。 */
extern volatile uint32 tick_1000us_cnt;

typedef struct
{
    uint32 imu_tick_count;
    uint32 control_tick_count;
    uint32 control_period_fault_count;
    uint32 background_coalesced_count;
    uint32 command_stale_count;
    uint32 imu_snapshot_fault_count;
    uint32 imu_stale_fault_count;
} car_realtime_diag_t;

extern volatile uint32 g_car_background_100hz_generation;
extern volatile car_realtime_diag_t g_car_realtime_diag;
extern volatile float g_car_speed_left_filtered;
extern volatile float g_car_speed_right_filtered;
extern volatile float g_car_yaw_feedback_deg;
extern volatile float g_car_base_speed_command;
extern volatile float g_car_base_speed_target;
extern volatile float g_car_speed_left_motor_output;
extern volatile float g_car_speed_right_motor_output;
extern volatile float Left_Target_Speed;
extern volatile float Right_Target_Speed;
extern volatile float mode1_speed_left_kp;
extern volatile float mode1_speed_left_ki;
extern volatile float mode1_speed_left_kd;
extern volatile float mode1_speed_right_kp;
extern volatile float mode1_speed_right_ki;
extern volatile float mode1_speed_right_kd;
extern volatile float mode1_speed_filter_alpha;
extern volatile float mode1_speed_ff_static;
extern volatile float mode1_gyroz_kp;
extern volatile float mode1_gyroz_ki;
extern volatile float mode1_gyroz_kff;
extern volatile float mode1_gyroz_k_turn;
extern volatile float mode1_yaw_kp;
extern volatile float mode1_yaw_kd;
extern volatile float mode1_plan_speed_limit_mps;
extern volatile float mode1_alignment_stop_deg;
extern volatile float mode1_wheel_target_limit;
extern volatile float mode1_speed_i_limit;
extern volatile float mode1_speed_ff_deadband;
extern volatile float mode1_speed_ff_transition;
extern volatile float mode1_speed_increment_limit;
extern volatile float mode1_speed_brake_static;
extern volatile float mode1_speed_decel_step;
extern volatile float mode1_gyroz_output_limit;
extern volatile float mode1_yaw_rate_limit_dps;
extern volatile float mode1_gyroz_stop_target_dps;
extern volatile float mode1_wheel_stop_speed;
extern volatile float mode1_large_turn_brake_speed;
extern volatile float mode1_large_turn_brake_target;
extern volatile float mode1_large_turn_brake_ff;
extern volatile float mode1_large_turn_brake_rate_dps;
extern volatile float mode1_large_turn_enter_deg;
extern volatile float mode1_large_turn_pivot_exit_deg;
extern volatile float mode1_large_turn_exit_start_deg;
extern volatile float mode1_large_turn_finish_deg;
extern volatile float mode1_large_turn_trigger_cycles;
extern volatile float mode1_large_turn_finish_cycles;
extern volatile float mode1_large_turn_timeout_cycles;
extern volatile float mode1_exit_command_match_deg;
extern volatile float mode1_brake_target_margin;
extern volatile float mode1_brake_ff_fade_span;
extern volatile float mode2_speed_left_kp;
extern volatile float mode2_speed_left_ki;
extern volatile float mode2_speed_left_kd;
extern volatile float mode2_speed_right_kp;
extern volatile float mode2_speed_right_ki;
extern volatile float mode2_speed_right_kd;
extern volatile float mode2_speed_filter_alpha;
extern volatile float mode2_speed_ff_static;
extern volatile float mode2_gyroz_kp;
extern volatile float mode2_gyroz_ki;
extern volatile float mode2_gyroz_kff;
extern volatile float mode2_gyroz_k_turn;
extern volatile float mode2_yaw_kp;
extern volatile float mode2_yaw_kd;
extern volatile float mode2_target_speed_mps;
extern volatile float mode2_input_deadzone;
extern volatile float mode2_alignment_stop_deg;
extern volatile float mode2_wheel_target_limit;
extern volatile float mode2_speed_i_limit;
extern volatile float mode2_speed_ff_deadband;
extern volatile float mode2_speed_ff_transition;
extern volatile float mode2_speed_increment_limit;
extern volatile float mode2_speed_brake_static;
extern volatile float mode2_speed_decel_step;
extern volatile float mode2_gyroz_output_limit;
extern volatile float mode2_yaw_rate_limit_dps;
extern volatile float mode2_gyroz_stop_target_dps;
extern volatile float mode2_wheel_stop_speed;
extern volatile float mode2_large_turn_brake_speed;
extern volatile float mode2_large_turn_brake_target;
extern volatile float mode2_large_turn_brake_ff;
extern volatile float mode2_large_turn_brake_rate_dps;
extern volatile float mode2_large_turn_enter_deg;
extern volatile float mode2_large_turn_pivot_exit_deg;
extern volatile float mode2_large_turn_exit_start_deg;
extern volatile float mode2_large_turn_finish_deg;
extern volatile float mode2_large_turn_trigger_cycles;
extern volatile float mode2_large_turn_finish_cycles;
extern volatile float mode2_large_turn_timeout_cycles;
extern volatile float mode2_exit_command_match_deg;
extern volatile float mode2_brake_target_margin;
extern volatile float mode2_brake_ff_fade_span;
extern volatile float mode4_speed_left_kp;
extern volatile float mode4_speed_left_ki;
extern volatile float mode4_speed_left_kd;
extern volatile float mode4_speed_right_kp;
extern volatile float mode4_speed_right_ki;
extern volatile float mode4_speed_right_kd;
extern volatile float mode4_speed_filter_alpha;
extern volatile float mode4_speed_ff_static;
extern volatile float mode4_gyroz_kp;
extern volatile float mode4_gyroz_ki;
extern volatile float mode4_gyroz_kff;
extern volatile float mode4_gyroz_k_turn;
extern volatile float mode4_yaw_kp;
extern volatile float mode4_yaw_kd;
extern volatile float mode4_plan_speed_limit_mps;
extern volatile float mode4_alignment_stop_deg;
extern volatile float mode4_wheel_target_limit;
extern volatile float mode4_speed_i_limit;
extern volatile float mode4_speed_ff_deadband;
extern volatile float mode4_speed_ff_transition;
extern volatile float mode4_speed_increment_limit;
extern volatile float mode4_speed_brake_static;
extern volatile float mode4_speed_decel_step;
extern volatile float mode4_gyroz_output_limit;
extern volatile float mode4_yaw_rate_limit_dps;
extern volatile float mode4_gyroz_stop_target_dps;
extern volatile float mode4_wheel_stop_speed;
extern volatile float mode4_large_turn_brake_speed;
extern volatile float mode4_large_turn_brake_target;
extern volatile float mode4_large_turn_brake_ff;
extern volatile float mode4_large_turn_brake_rate_dps;
extern volatile float mode4_large_turn_enter_deg;
extern volatile float mode4_large_turn_pivot_exit_deg;
extern volatile float mode4_large_turn_exit_start_deg;
extern volatile float mode4_large_turn_finish_deg;
extern volatile float mode4_large_turn_trigger_cycles;
extern volatile float mode4_large_turn_finish_cycles;
extern volatile float mode4_large_turn_timeout_cycles;
extern volatile float mode4_exit_command_match_deg;
extern volatile float mode4_brake_target_margin;
extern volatile float mode4_brake_ff_fade_span;
extern volatile float mode5_speed_left_kp;
extern volatile float mode5_speed_left_ki;
extern volatile float mode5_speed_left_kd;
extern volatile float mode5_speed_right_kp;
extern volatile float mode5_speed_right_ki;
extern volatile float mode5_speed_right_kd;
extern volatile float mode5_speed_filter_alpha;
extern volatile float mode5_speed_ff_static;
extern volatile float mode5_gyroz_kp;
extern volatile float mode5_gyroz_ki;
extern volatile float mode5_gyroz_kff;
extern volatile float mode5_gyroz_k_turn;
extern volatile float mode5_yaw_kp;
extern volatile float mode5_yaw_kd;
extern volatile float mode5_target_speed_mps;
extern volatile float mode5_input_deadzone;
extern volatile float mode5_alignment_stop_deg;
extern volatile float mode5_wheel_target_limit;
extern volatile float mode5_speed_i_limit;
extern volatile float mode5_speed_ff_deadband;
extern volatile float mode5_speed_ff_transition;
extern volatile float mode5_speed_increment_limit;
extern volatile float mode5_speed_brake_static;
extern volatile float mode5_speed_decel_step;
extern volatile float mode5_gyroz_output_limit;
extern volatile float mode5_yaw_rate_limit_dps;
extern volatile float mode5_gyroz_stop_target_dps;
extern volatile float mode5_wheel_stop_speed;
extern volatile float mode5_large_turn_brake_speed;
extern volatile float mode5_large_turn_brake_target;
extern volatile float mode5_large_turn_brake_ff;
extern volatile float mode5_large_turn_brake_rate_dps;
extern volatile float mode5_large_turn_enter_deg;
extern volatile float mode5_large_turn_pivot_exit_deg;
extern volatile float mode5_large_turn_exit_start_deg;
extern volatile float mode5_large_turn_finish_deg;
extern volatile float mode5_large_turn_trigger_cycles;
extern volatile float mode5_large_turn_finish_cycles;
extern volatile float mode5_large_turn_timeout_cycles;
extern volatile float mode5_exit_command_match_deg;
extern volatile float mode5_brake_target_margin;
extern volatile float mode5_brake_ff_fade_span;
extern volatile float mode8_speed_left_kp;
extern volatile float mode8_speed_left_ki;
extern volatile float mode8_speed_left_kd;
extern volatile float mode8_speed_right_kp;
extern volatile float mode8_speed_right_ki;
extern volatile float mode8_speed_right_kd;
extern volatile float mode8_speed_filter_alpha;
extern volatile float mode8_speed_ff_static;
extern volatile float mode8_target_speed_mps;
extern volatile float mode8_speed_i_limit;
extern volatile float mode8_speed_ff_deadband;
extern volatile float mode8_speed_ff_transition;
extern volatile float mode8_speed_increment_limit;
extern volatile float g_car_gyroz_feedback_dps;

extern volatile float g_air_tof_fused_height_mm;
extern volatile float g_air_euler_roll;
extern volatile float g_air_euler_pitch;
extern volatile float g_air_euler_yaw;
extern volatile float g_air_pos_est_vel_x;
extern volatile float g_air_pos_est_vel_y;
extern volatile float g_air_state;

typedef struct
{
    float tof_raw_height_mm[4];
    float flow_raw_x;
    float flow_raw_y;
    float flow_filtered_x;
    float flow_filtered_y;
    float imu_raw_gyro[3];
    float imu_raw_acc[3];
    float imu_filtered_gyro[3];
    float imu_filtered_acc[3];
    float camera_spi_online[2];
    float camera_spi_ready[2];
    float camera_spi_error_code;
    float camera_spi_rx_head[2][2];
} air_diag_telemetry_t;

extern volatile air_diag_telemetry_t g_air_diag_telemetry;

extern volatile float g_air_std_ch0;
extern volatile float g_air_std_ch1;
extern volatile float g_air_std_ch2;
extern volatile float g_air_std_ch3;
extern volatile float g_air_std_ch4;
extern volatile float g_air_std_ch5;
extern volatile float g_air_std_ch6;
extern volatile float g_air_std_ch7;
extern volatile float g_air_std_ch8;
extern volatile float g_air_yaw_angle_target_deg;
extern volatile float g_air_sync_time_ms;
extern volatile float g_air_car_plan_valid;
extern volatile float g_air_car_plan_strafe_mps;
extern volatile float g_air_car_plan_forward_mps;
extern volatile float g_air_car_plan_camera;
extern volatile float g_air_car_plan_beacon_index;
extern volatile float g_air_car_plan_dist_px;
extern volatile float g_air_beacon_lost_flag;

uint8 car_menu_is_runtime_locked(void);
void car_pwm_test_control(uint8 active, int16 left_pwm, int16 right_pwm);
void car_loop_init(void);
void car_loop_poll(void);
void car_loop_imu_1000HZ_isr(void);
void car_loop_motion_100HZ_isr(void);
void car_loop_release_background_100HZ_isr(void);

#endif
